Looks like rvm doesn't use repos directory any more.

diff --git a/script/rvm-install-tf b/script/rvm-install-tf
--- a/script/rvm-install-tf
+++ b/script/rvm-install-tf
@@ -10,10 +10,10 @@ if [[ -z $rvm_path ]] ; then
     echo 'Variable $rvm_path seems not to be set. Is rvm in use? Aborting.' 1>&2
     exit 2
 fi
-if [[ ! -d $rvm_path/repos ]] ; then
-    echo '$rvm_path/repos does is not a directory. Is rvm in use? Aborting.' 1>&2
-    exit 3
-fi
+# if [[ ! -d $rvm_path/repos ]] ; then
+#     echo '$rvm_path/repos does is not a directory. Is rvm in use? Aborting.' 1>&2
+#     exit 3
+# fi
 
 if cmp /bin/sh /bin/dash 2>/dev/null >/dev/null; then
     echo 'Warning your /bin/sh is dash. Making Ruby might not work!' 1>&2
